# GENERATE TIME: Sun Mar 22 09:20:24 2026
# CMD:
# pydiff/train.py -opt options/unet_sp_attn.yaml

# general settings
name: unet_sp_attn_lsui
model_type: PyDiffModel
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    dataset_names: ['uieb']
    use_rrdb: false
    name: train
    type: UW_Dataset_Preloaded2
    gt_root: "../../dataset/UW/gt"
    input_root: "../../dataset/UW/input"
    concat_with_position_encoding: true
    concat_with_hiseq: true
    hiseq_random_cat: false
    mean: [0.23976195, 0.4732557,  0.44424778]
    std: [0.19079739, 0.20718611, 0.21206066]
    should_normalize: true
    use_flip: true

    bright_aug: false
    bright_aug_range: [0.5, 1.5]

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    input_mode: crop
    crop_size: 256
    should_pad: true

  val:
    # Please modify accordingly to use your own validation
    # Or comment the val block if do not need validation during training
    dataset_names: ['lsui']
    use_rrdb: false
    name: validation
    type: UW_Dataset_Preloaded2
    gt_root: "../../dataset/UW/gt"
    input_root: "../../dataset/UW/input"
    concat_with_hiseq: true
    divide: 32
    concat_with_position_encoding: true
    mean: [0.23976195, 0.4732557,  0.44424778]
    std: [0.19079739, 0.20718611, 0.21206066]
    should_normalize: true
    input_mode: crop
    crop_size: 256
    should_pad: true

# network structures
network_unet:
  type: SR3UNet
  in_channel: 13
  out_channel: 3
  inner_channel: 64
  norm_groups: 32
  channel_mults: [1,2,4,8,8]
  attn_res: [16]
  res_blocks: 2
  dropout: 0.1
  divide: 16
  use_CA: false
  attn_type: SHAV2
  use_affine_level: true
  

network_global_corrector:
  type: GlobalCorrector
  normal01: true

network_ddpm:
  type: GaussianDiffusion
  image_size: 256
  channels: 3
  conditional: true
  color_limit: -1
  pyramid_list: [1, 1, 2, 4]

ddpm_schedule:
  schedule: "linear"
  n_timestep: 2000
  linear_start: !!float 1e-6
  linear_end: !!float 1e-2

# path
path:
  pretrain_network_g: /app/pretrained_models/unet_sp_attn.pth
  param_key_g: params
  strict_load_g: False
  pretrain_network_d: ~
  resume_state: ~
  ignore_resume_networks: ['network_identity']

# training settings
train:
  cs_on_shift: true
  vis_train: true
  vis_num: 150
  train_type: ddpm_cs_pyramid
  t_border: 1000
  input_mode: crop
  crop_size: [256, 256]
  optim_g:
    type: Adam
    lr: !!float 3.125e-6
  optim_d:
    type: Adam
    lr: !!float 6.25e-5
  optim_component:
    type: Adam
    lr: !!float 6.25e-5

  scheduler:
    type: MultiStepLR
    milestones: []
    gamma: 0.5

  total_iter: 0
  warmup_iter: -1  # no warm up

# validation settings
val:
  split_log: true
  fix_seed: true
  color_gamma: 1.0
  use_up_v2: true
  pyramid_list: [1, 1, 2, 4]
  ddim_eta: !!float 1.0
  ddim_timesteps: 4
  use_kind_align: false
  cal_all: true
  show_all: true
  val_freq: !!float 250000
  save_img: true
  only_save_sr: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr_default
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim_default
    lpips:
      type: calculate_lpips_default


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 50000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true